-- FR-01: Co so du lieu tap trung ve hang ton kho (item, vi tri, lo/batch)
-- Scope: SUPPLIER, WAREHOUSE, LOCATION, ITEM, LOT, INVENTORY_BALANCE
-- Target schema: ADMIN (parsing schema of APEX app 105 / 26house)
-- Note: constraint names are schema-wide unique in Oracle; this schema already
-- has a legacy STOCK_* object set, so new constraint names avoid its prefixes
-- (e.g. LOT_* -> LOTM_*) instead of colliding with it.

set define off

--------------------------------------------------------------------------------
-- SUPPLIER
--------------------------------------------------------------------------------
create table supplier (
    supplier_id      number generated by default on null as identity
                      constraint supplier_pk primary key,
    supplier_code    varchar2(20)  not null,
    supplier_name    varchar2(150) not null,
    contact_name     varchar2(100),
    contact_email    varchar2(120),
    contact_phone    varchar2(30),
    integration_ref  varchar2(60),
    is_active        char(1) default 'Y' not null,
    created_by       varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on       date default sysdate not null,
    updated_by       varchar2(60),
    updated_on       date,
    constraint supplier_code_uk unique (supplier_code),
    constraint supplier_active_ck check (is_active in ('Y','N'))
);
comment on table supplier is 'FR-01: nha cung cap, phuc vu truy vet lo hang va tich hop ke toan tuong lai (FR-09)';

--------------------------------------------------------------------------------
-- WAREHOUSE
--------------------------------------------------------------------------------
create table warehouse (
    warehouse_id     number generated by default on null as identity
                      constraint warehouse_pk primary key,
    warehouse_code   varchar2(10)  not null,
    warehouse_name   varchar2(100) not null,
    address          varchar2(200),
    is_active        char(1) default 'Y' not null,
    created_by       varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on       date default sysdate not null,
    updated_by       varchar2(60),
    updated_on       date,
    constraint warehouse_code_uk unique (warehouse_code),
    constraint warehouse_active_ck check (is_active in ('Y','N'))
);
comment on table warehouse is 'FR-01: kho vat ly, san sang multi-site';

--------------------------------------------------------------------------------
-- LOCATION (bin)
--------------------------------------------------------------------------------
create table location (
    location_id      number generated by default on null as identity
                      constraint location_pk primary key,
    warehouse_id      number not null,
    location_code     varchar2(30) not null,
    zone              varchar2(20),
    aisle             varchar2(10),
    rack              varchar2(10),
    shelf             varchar2(10),
    bin_code          varchar2(30),
    location_type     varchar2(20) default 'BULK' not null,
    capacity_uom      varchar2(20),
    capacity_qty      number(12,2),
    is_active         char(1) default 'Y' not null,
    created_by        varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on        date default sysdate not null,
    updated_by        varchar2(60),
    updated_on        date,
    constraint location_wh_code_uk unique (warehouse_id, location_code),
    constraint location_wh_fk foreign key (warehouse_id) references warehouse (warehouse_id),
    constraint location_type_ck check (location_type in
        ('RECEIVING','PICK_FACE','BULK','QUARANTINE','STAGING','SHIPPING')),
    constraint location_active_ck check (is_active in ('Y','N'))
);
comment on table location is 'FR-01/FR-05: vi tri luu tru (bin) trong kho, dung cho phan bo va toi uu tuyen duong lay hang';

create index location_type_idx on location (location_type);

--------------------------------------------------------------------------------
-- ITEM (SKU / device catalog)
--------------------------------------------------------------------------------
create table item (
    item_id            number generated by default on null as identity
                       constraint item_pk primary key,
    item_code          varchar2(30)  not null,
    item_name          varchar2(200) not null,
    device_category    varchar2(40)  not null,
    uom                varchar2(20)  default 'EA' not null,
    barcode_value      varchar2(64),
    qr_value           varchar2(128),
    manufacturer       varchar2(100),
    model_no           varchar2(100),
    is_lot_tracked     char(1) default 'Y' not null,
    min_qty            number(12,2) default 0 not null,
    max_qty            number(12,2),
    reorder_point      number(12,2) default 0 not null,
    default_supplier_id number,
    is_active          char(1) default 'Y' not null,
    created_by         varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on         date default sysdate not null,
    updated_by         varchar2(60),
    updated_on         date,
    constraint item_code_uk unique (item_code),
    constraint item_supplier_fk foreign key (default_supplier_id) references supplier (supplier_id),
    constraint item_lot_tracked_ck check (is_lot_tracked in ('Y','N')),
    constraint item_active_ck check (is_active in ('Y','N')),
    constraint item_device_category_ck check (device_category in (
        'BIOMETRIC_READER','CHIP_CARD_READER','MONITOR','TV_DISPLAY','TABLET',
        'MOBILE_DEVICE','E_POSTER','SPEAKER','DIGITAL_SIGNATURE_READER','MEDIA_PLAYER','OTHER'
    ))
);
comment on table item is 'FR-01: danh muc SKU/thiet bi (10.000+), nguon cho faceted-search va scan lookup';

create index item_device_category_idx on item (device_category);
create index item_barcode_idx on item (barcode_value);
create index item_active_idx on item (is_active);

--------------------------------------------------------------------------------
-- LOT (batch)
--------------------------------------------------------------------------------
create table lot (
    lot_id             number generated by default on null as identity
                       constraint lotm_pk primary key,
    item_id            number not null,
    lot_number         varchar2(60) not null,
    supplier_id        number,
    manufacture_date   date,
    expiry_date        date,
    qc_status          varchar2(10) default 'PENDING' not null,
    created_by         varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on         date default sysdate not null,
    updated_by         varchar2(60),
    updated_on         date,
    constraint lotm_item_lotno_uk unique (item_id, lot_number),
    constraint lotm_item_fk foreign key (item_id) references item (item_id),
    constraint lotm_supplier_fk foreign key (supplier_id) references supplier (supplier_id),
    constraint lotm_qc_status_ck check (qc_status in ('PENDING','PASSED','FAILED','HOLD'))
);
comment on table lot is 'FR-01: so lo/batch cua tung item, qc_status se duoc PKG_QUALITY (Phase 4) kiem tra truoc khi cho phep xuat';

create index lotm_item_idx on lot (item_id);

--------------------------------------------------------------------------------
-- INVENTORY_BALANCE (item x location x lot)
--------------------------------------------------------------------------------
create table inventory_balance (
    inventory_balance_id number generated by default on null as identity
                          constraint inventory_balance_pk primary key,
    item_id              number not null,
    location_id          number not null,
    lot_id               number,
    -- Oracle unique constraints treat NULL as distinct values, which would allow
    -- duplicate (item_id, location_id) rows for non-lot-tracked items (lot_id null).
    -- lot_id_key collapses NULL to 0 so the uniqueness rule below actually holds.
    lot_id_key           number generated always as (nvl(lot_id, 0)) virtual,
    qty_on_hand          number(14,2) default 0 not null,
    qty_allocated        number(14,2) default 0 not null,
    qty_available         number(14,2) generated always as (qty_on_hand - qty_allocated) virtual,
    last_counted_date     date,
    updated_on            date default sysdate not null,
    constraint invbal_item_loc_lot_uk unique (item_id, location_id, lot_id_key),
    constraint invbal_item_fk foreign key (item_id) references item (item_id),
    constraint invbal_location_fk foreign key (location_id) references location (location_id),
    constraint invbal_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint invbal_onhand_ck check (qty_on_hand >= 0),
    constraint invbal_allocated_ck check (qty_allocated >= 0),
    constraint invbal_alloc_le_onhand_ck check (qty_allocated <= qty_on_hand)
);
comment on table inventory_balance is 'FR-01/FR-06: ton kho hien tai theo item+vi tri+lo, cap nhat real-time';

create index invbal_location_idx on inventory_balance (location_id);
create index invbal_lot_idx on inventory_balance (lot_id);

--------------------------------------------------------------------------------
-- Reporting view: real-time inventory (FR-06 preview, uses FR-01 tables)
--------------------------------------------------------------------------------
create or replace view v_inventory_current as
select
    ib.inventory_balance_id,
    i.item_id,
    i.item_code,
    i.item_name,
    i.device_category,
    w.warehouse_id,
    w.warehouse_code,
    l.location_id,
    l.location_code,
    l.location_type,
    lt.lot_id,
    lt.lot_number,
    lt.qc_status,
    ib.qty_on_hand,
    ib.qty_allocated,
    ib.qty_available,
    ib.last_counted_date,
    ib.updated_on
from inventory_balance ib
join item i     on i.item_id = ib.item_id
join location l on l.location_id = ib.location_id
join warehouse w on w.warehouse_id = l.warehouse_id
left join lot lt on lt.lot_id = ib.lot_id;
comment on table v_inventory_current is 'FR-06: view ton kho real-time theo item/vi tri/lo, dung cho dashboard va IG';
