-- FR-01/FR-06: immutable inventory transaction ledger
-- Every balance mutation in INVENTORY_BALANCE must post one row here (via PKG_INVENTORY.post_transaction).

set define off

create table inventory_transaction (
    txn_id            number generated by default on null as identity
                      constraint invtxn_pk primary key,
    item_id           number not null,
    location_id       number not null,
    lot_id            number,
    txn_type          varchar2(20) not null,
    qty               number(14,2) not null,
    txn_ts            timestamp default systimestamp not null,
    source_doc_type   varchar2(30),
    source_doc_id     number,
    notes             varchar2(400),
    created_by        varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint invtxn_item_fk foreign key (item_id) references item (item_id),
    constraint invtxn_location_fk foreign key (location_id) references location (location_id),
    constraint invtxn_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint invtxn_type_ck check (txn_type in (
        'RECEIPT','PUTAWAY','MOVE','PICK','PACK','SHIP','ADJUST','QC_HOLD','QC_RELEASE','COUNT'
    )),
    constraint invtxn_qty_not_zero_ck check (qty <> 0)
);
comment on table inventory_transaction is 'FR-01/FR-06: immutable ledger of every inventory balance change, source of truth for KPI evidence (accuracy, cycle time)';

create index invtxn_item_loc_lot_idx on inventory_transaction (item_id, location_id, lot_id);
create index invtxn_source_doc_idx on inventory_transaction (source_doc_type, source_doc_id);
create index invtxn_txn_ts_idx on inventory_transaction (txn_ts);
