-- FR-02: automated inbound receiving (goods receipt), real-time inventory recording.

set define off

create table inbound_receipt (
    receipt_id      number generated by default on null as identity
                    constraint inbrcpt_pk primary key,
    supplier_id     number,
    po_reference    varchar2(40),
    warehouse_id    number not null,
    expected_date   date,
    status          varchar2(15) default 'EXPECTED' not null,
    received_by     varchar2(60),
    created_by      varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on      date default sysdate not null,
    updated_by      varchar2(60),
    updated_on      date,
    constraint inbrcpt_supplier_fk foreign key (supplier_id) references supplier (supplier_id),
    constraint inbrcpt_wh_fk foreign key (warehouse_id) references warehouse (warehouse_id),
    constraint inbrcpt_status_ck check (status in ('EXPECTED','RECEIVING','COMPLETED','CLOSED'))
);
comment on table inbound_receipt is 'FR-02: inbound receipt header (goods receipt document)';

create index inbrcpt_supplier_idx on inbound_receipt (supplier_id);
create index inbrcpt_status_idx on inbound_receipt (status);

create table inbound_receipt_line (
    line_id              number generated by default on null as identity
                         constraint inbline_pk primary key,
    receipt_id           number not null,
    item_id               number not null,
    lot_id                number,
    expected_qty          number(14,2) not null,
    received_qty          number(14,2) default 0 not null,
    putaway_location_id   number,
    status                varchar2(15) default 'PENDING' not null,
    created_by            varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on            date default sysdate not null,
    updated_by            varchar2(60),
    updated_on            date,
    constraint inbline_receipt_fk foreign key (receipt_id) references inbound_receipt (receipt_id) on delete cascade,
    constraint inbline_item_fk foreign key (item_id) references item (item_id),
    constraint inbline_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint inbline_loc_fk foreign key (putaway_location_id) references location (location_id),
    constraint inbline_expected_ck check (expected_qty > 0),
    constraint inbline_received_ck check (received_qty >= 0),
    constraint inbline_status_ck check (status in ('PENDING','RECEIVED','PUTAWAY','SHORT','CANCELLED'))
);
comment on table inbound_receipt_line is 'FR-02: inbound receipt line, one row per item/lot expected on a receipt';

create index inbline_receipt_idx on inbound_receipt_line (receipt_id);
create index inbline_item_idx on inbound_receipt_line (item_id);
