-- FR-04: ship-to party for outbound orders.

set define off

create table customer (
    customer_id      number generated by default on null as identity
                     constraint customer_pk primary key,
    customer_code    varchar2(20)  not null,
    customer_name    varchar2(150) not null,
    address          varchar2(200),
    integration_ref  varchar2(60),
    is_active        char(1) default 'Y' not null,
    created_by       varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on       date default sysdate not null,
    updated_by       varchar2(60),
    updated_on       date,
    constraint customer_code_uk unique (customer_code),
    constraint customer_active_ck check (is_active in ('Y','N'))
);
comment on table customer is 'FR-04: ship-to party for outbound orders, integration_ref for future e-shop link (FR-09)';
