-- FR-03/FR-04/FR-05: outbound order -> allocation -> pick -> pack -> ship,
-- with pick-path sequencing by location zone/aisle/rack (FR-05) and
-- barcode/QR scan confirmation on PICK_TASK (FR-03).
--
-- Order line state machine (OUTBOUND_ORDER_LINE.status):
--   PENDING -> ALLOCATED -> PICKED -> (SHORT if never fully allocated)
-- Order header state machine (OUTBOUND_ORDER.status):
--   RECEIVED -> ALLOCATED -> PICKING -> PICKED -> PACKED -> SHIPPED -> CANCELLED

set define off

create table outbound_order (
    order_id            number generated by default on null as identity
                        constraint oborder_pk primary key,
    order_number         varchar2(30) not null,
    customer_id          number not null,
    warehouse_id         number not null,
    order_source         varchar2(20) default 'MANUAL' not null,
    order_date           date default sysdate not null,
    required_ship_date   date,
    priority             varchar2(10) default 'NORMAL' not null,
    status                varchar2(15) default 'RECEIVED' not null,
    created_by            varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on            date default sysdate not null,
    updated_by            varchar2(60),
    updated_on            date,
    constraint oborder_number_uk unique (order_number),
    constraint oborder_customer_fk foreign key (customer_id) references customer (customer_id),
    constraint oborder_wh_fk foreign key (warehouse_id) references warehouse (warehouse_id),
    constraint oborder_source_ck check (order_source in ('MANUAL','ESHOP_API','EDI')),
    constraint oborder_priority_ck check (priority in ('LOW','NORMAL','HIGH','URGENT')),
    constraint oborder_status_ck check (status in
        ('RECEIVED','ALLOCATED','PICKING','PICKED','PACKED','SHIPPED','CANCELLED'))
);
comment on table outbound_order is 'FR-04: outbound order header, drives the received->allocated->picking->picked->packed->shipped state machine';

create index oborder_customer_idx on outbound_order (customer_id);
create index oborder_status_idx on outbound_order (status);

create table outbound_order_line (
    line_id       number generated by default on null as identity
                  constraint obline_pk primary key,
    order_id       number not null,
    item_id        number not null,
    qty_ordered    number(14,2) not null,
    qty_allocated  number(14,2) default 0 not null,
    qty_picked     number(14,2) default 0 not null,
    qty_shipped    number(14,2) default 0 not null,
    status         varchar2(15) default 'PENDING' not null,
    created_by     varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on     date default sysdate not null,
    updated_by     varchar2(60),
    updated_on     date,
    constraint obline_order_fk foreign key (order_id) references outbound_order (order_id) on delete cascade,
    constraint obline_item_fk foreign key (item_id) references item (item_id),
    constraint obline_qty_ordered_ck check (qty_ordered > 0),
    constraint obline_status_ck check (status in ('PENDING','ALLOCATED','PICKED','SHORT','CANCELLED'))
);
comment on table outbound_order_line is 'FR-04: outbound order line; PICK_TASK rows record which location/lot actually fulfil it (one line can span several tasks)';

create index obline_order_idx on outbound_order_line (order_id);
create index obline_item_idx on outbound_order_line (item_id);

create table pick_wave (
    wave_id     number generated by default on null as identity
                constraint pkwave_pk primary key,
    wave_date   date default sysdate not null,
    status      varchar2(15) default 'PLANNED' not null,
    created_by  varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on  date default sysdate not null,
    constraint pkwave_status_ck check (status in ('PLANNED','RELEASED','COMPLETED','CANCELLED'))
);
comment on table pick_wave is 'FR-05: optional batch grouping of pick tasks released together';

create table pick_task (
    task_id           number generated by default on null as identity
                      constraint pktask_pk primary key,
    order_line_id      number not null,
    wave_id            number,
    item_id            number not null,
    lot_id             number,
    from_location_id   number not null,
    qty_requested      number(14,2) not null,
    qty_picked         number(14,2) default 0 not null,
    sequence_no        number,
    assigned_to        varchar2(60),
    status             varchar2(15) default 'PENDING' not null,
    scanned_code       varchar2(64),
    scan_ts            timestamp,
    created_by         varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on         date default sysdate not null,
    updated_by         varchar2(60),
    updated_on         date,
    constraint pktask_line_fk foreign key (order_line_id) references outbound_order_line (line_id) on delete cascade,
    constraint pktask_wave_fk foreign key (wave_id) references pick_wave (wave_id),
    constraint pktask_item_fk foreign key (item_id) references item (item_id),
    constraint pktask_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint pktask_loc_fk foreign key (from_location_id) references location (location_id),
    constraint pktask_qty_req_ck check (qty_requested > 0),
    constraint pktask_status_ck check (status in
        ('PENDING','ASSIGNED','IN_PROGRESS','PICKED','SHORT','CANCELLED'))
);
comment on table pick_task is 'FR-03/FR-05: one pick instruction (item/lot/qty at a specific bin), SEQUENCE_NO orders the pick path by zone/aisle/rack; SCANNED_CODE/SCAN_TS record the barcode/QR confirmation';

create index pktask_line_idx on pick_task (order_line_id);
create index pktask_wave_idx on pick_task (wave_id);
create index pktask_status_idx on pick_task (status);

create table ship_package (
    package_id     number generated by default on null as identity
                   constraint shpkg_pk primary key,
    order_id        number not null,
    package_type    varchar2(20) default 'BOX' not null,
    weight          number(10,2),
    status          varchar2(15) default 'OPEN' not null,
    packed_by       varchar2(60),
    created_on      date default sysdate not null,
    constraint shpkg_order_fk foreign key (order_id) references outbound_order (order_id) on delete cascade,
    constraint shpkg_status_ck check (status in ('OPEN','PACKED','SHIPPED'))
);
comment on table ship_package is 'FR-04: shipping carton/parcel packed from one order''s picked lines';

create index shpkg_order_idx on ship_package (order_id);

create table ship_package_line (
    package_line_id  number generated by default on null as identity
                     constraint shpkgl_pk primary key,
    package_id        number not null,
    order_line_id      number not null,
    item_id            number not null,
    lot_id             number,
    qty                number(14,2) not null,
    constraint shpkgl_pkg_fk foreign key (package_id) references ship_package (package_id) on delete cascade,
    constraint shpkgl_line_fk foreign key (order_line_id) references outbound_order_line (line_id),
    constraint shpkgl_item_fk foreign key (item_id) references item (item_id),
    constraint shpkgl_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint shpkgl_qty_ck check (qty > 0)
);
comment on table ship_package_line is 'FR-04: item/qty content of one shipping package';

create index shpkgl_pkg_idx on ship_package_line (package_id);

create table shipment (
    shipment_id            number generated by default on null as identity
                           constraint ship_pk primary key,
    order_id                number not null,
    carrier                 varchar2(60),
    tracking_number         varchar2(60),
    ship_date               date,
    status                  varchar2(15) default 'PENDING' not null,
    ship_from_warehouse_id  number,
    created_on              date default sysdate not null,
    constraint ship_order_fk foreign key (order_id) references outbound_order (order_id),
    constraint ship_wh_fk foreign key (ship_from_warehouse_id) references warehouse (warehouse_id),
    constraint ship_status_ck check (status in ('PENDING','SHIPPED'))
);
comment on table shipment is 'FR-04: shipment/manifest record for a shipped order';

create index ship_order_idx on shipment (order_id);
