-- FR-10: baseline + target for the 3 OIP-mandated KPIs.
-- IS_PLACEHOLDER = 'Y' rows hold FAKE demo figures for development/testing
-- only. Per the OIP guidance quoted in 26house-new-system.docx, the
-- pre-system baseline MUST be an actually measured figure or the required
-- improvement cannot be proven -- placeholder rows must be replaced with
-- real measured baselines (and IS_PLACEHOLDER set to 'N') before UAT/audit.

set define off

create table kpi_baseline (
    kpi_id                number generated by default on null as identity
                          constraint kpibase_pk primary key,
    kpi_code               varchar2(30)  not null,
    kpi_name                varchar2(150) not null,
    unit                     varchar2(30)  not null,
    direction                varchar2(10)  not null,
    baseline_value           number(14,2),
    baseline_measured_from   date,
    baseline_measured_to     date,
    baseline_note            varchar2(400),
    target_value             number(14,2),
    oip_ref                  varchar2(300),
    is_placeholder           char(1) default 'Y' not null,
    created_on               date default sysdate not null,
    updated_on               date,
    constraint kpibase_code_uk unique (kpi_code),
    constraint kpibase_direction_ck check (direction in ('HIGHER','LOWER')),
    constraint kpibase_placeholder_ck check (is_placeholder in ('Y','N'))
);
comment on table kpi_baseline is 'FR-10: baseline/target for the 3 OIP KPIs; IS_PLACEHOLDER=Y means fake demo data, must be replaced with real measured figures before UAT';
