-- FR-07: quality management. QUALITY_INSPECTION records a pass/fail/conditional
-- check and drives LOT.qc_status via PKG_QUALITY.record_inspection.
-- QUALITY_HOLD is a finer-grained hold than LOT.qc_status: it can target one
-- item+lot+location combination (or a whole item/lot if location_id is null,
-- or a whole item if lot_id is also null) without changing the lot's overall
-- QC status. Both are enforced in PKG_OUTBOUND.allocate_line so held stock
-- is never allocated to an outbound order.

set define off

create table quality_inspection (
    inspection_id   number generated by default on null as identity
                    constraint qinsp_pk primary key,
    source_type     varchar2(20) not null,
    source_id       number,
    item_id         number not null,
    lot_id          number,
    inspector       varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    inspection_date date default sysdate not null,
    result          varchar2(15) not null,
    defect_code     varchar2(30),
    notes           varchar2(400),
    constraint qinsp_item_fk foreign key (item_id) references item (item_id),
    constraint qinsp_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint qinsp_source_type_ck check (source_type in ('INBOUND_LINE','LOT','RETURN')),
    constraint qinsp_result_ck check (result in ('PASS','FAIL','CONDITIONAL'))
);
comment on table quality_inspection is 'FR-07: quality inspection record; PASS/FAIL results drive LOT.qc_status via PKG_QUALITY.record_inspection';

create index qinsp_item_idx on quality_inspection (item_id);
create index qinsp_lot_idx on quality_inspection (lot_id);

create table quality_hold (
    hold_id       number generated by default on null as identity
                  constraint qhold_pk primary key,
    item_id       number not null,
    lot_id        number,
    location_id   number,
    reason        varchar2(200) not null,
    hold_date     date default sysdate not null,
    released_by   varchar2(60),
    release_date  date,
    status        varchar2(10) default 'ACTIVE' not null,
    created_by    varchar2(60) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on    date default sysdate not null,
    constraint qhold_item_fk foreign key (item_id) references item (item_id),
    constraint qhold_lot_fk foreign key (lot_id) references lot (lot_id),
    constraint qhold_loc_fk foreign key (location_id) references location (location_id),
    constraint qhold_status_ck check (status in ('ACTIVE','RELEASED'))
);
comment on table quality_hold is 'FR-07: stock hold, NULL lot_id/location_id means the hold applies to every lot/location of that item; enforced in PKG_OUTBOUND.allocate_line';

create index qhold_item_lot_loc_idx on quality_hold (item_id, lot_id, location_id);
create index qhold_status_idx on quality_hold (status);
