-- FR-09: integration readiness. Architecture/API points for future e-shop
-- and accounting integration -- staged as core WMS infrastructure per
-- PROJECT-PLAN.md compliance framing, not a separate billed project.

set define off

create table integration_endpoint_config (
    endpoint_id    number generated by default on null as identity
                   constraint intgcfg_pk primary key,
    system_name    varchar2(30) not null,
    endpoint_url   varchar2(300),
    auth_method    varchar2(30),
    active_flag    char(1) default 'Y' not null,
    created_on     date default sysdate not null,
    constraint intgcfg_system_ck check (system_name in ('ESHOP','ACCOUNTING')),
    constraint intgcfg_active_ck check (active_flag in ('Y','N'))
);
comment on table integration_endpoint_config is 'FR-09: endpoint config only; real credentials live in the APEX workspace credential store, not here';

create table integration_log (
    log_id             number generated by default on null as identity
                       constraint intglog_pk primary key,
    direction           varchar2(10) not null,
    integration_type    varchar2(30) not null,
    payload             clob,
    status               varchar2(15) default 'RECEIVED' not null,
    error_message        varchar2(4000),
    related_order_id     number,
    idempotency_key       varchar2(100),
    created_date          date default sysdate not null,
    constraint intglog_order_fk foreign key (related_order_id) references outbound_order (order_id),
    constraint intglog_direction_ck check (direction in ('INBOUND', 'OUTBOUND')),
    constraint intglog_status_ck check (status in ('RECEIVED', 'PROCESSED', 'ERROR')),
    constraint intglog_idem_uk unique (idempotency_key)
);
comment on table integration_log is 'FR-09: inbound/outbound integration staging log; idempotency_key lets retried inbound payloads no-op instead of double-applying';

create index intglog_status_idx on integration_log (status);
create index intglog_order_idx on integration_log (related_order_id);
